apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-sidecars
  namespace: monitoring
  labels:
    app.kubernetes.io/name: observability
spec:
  selector:
    matchExpressions:
      - key: service.istio.io/canonical-name
        operator: Exists
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /stats/prometheus
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_ip]
          action: replace
          targetLabel: __address__
          replacement: "${1}:15090"
