apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/name: observability
spec:
  selector:
    matchLabels:
      app: istiod
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 30s
