apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/toreau/k8s-research.git
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
