apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git://host.docker.internal:9418/k8s-research
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
