apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: frosta-historielag
  namespace: frosta-historielag
spec:
  image: ghcr.io/toreau/frosta-historielag.no@sha256:89940b8d540836923763296bde4f70efdfd3b8184c5598aec1005b05681a36f4
  port: 8080
  ingresses:
    - frosta-historielag.no.172.21.255.200.nip.io
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
