apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: frosta-historielag
  namespace: frosta-historielag
spec:
  image: ghcr.io/toreau/frosta-historielag.no@sha256:c5c316e06cc117c3917412fa370ac8255f08d4674feab32d4ddbd4f33799b82d
  port: 8080
  ingresses:
    - frosta-historielag.no.172.21.255.200.nip.io
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
