apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: frosta-historielag
  namespace: frosta-historielag
spec:
  image: ghcr.io/toreau/frosta-historielag.no@sha256:4ee87c2408f817116bdd315184fe376de70fb36791bf6f37dd167ffa10d0f215
  port: 8080
  ingresses:
    - frosta-historielag.no.172.21.255.200.nip.io
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
