apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-datasets
  namespace: astronomy
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: github-auth
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: ingest
          image: ghcr.io/toreau/astronomy-api@sha256:ee45e5be89c0dc2798b9b7097e1d9277ef17f020688c0039487ae64501abb4b5
          command:
            - /bin/sh
            - -c
            - >-
              dotnet Astronomy.DataIngestion.dll ingest eop &&
              dotnet Astronomy.DataIngestion.dll ingest eop-c04 &&
              dotnet Astronomy.DataIngestion.dll ingest leap-seconds &&
              dotnet Astronomy.DataIngestion.dll ingest star-catalog &&
              dotnet Astronomy.DataIngestion.dll dataset status
          envFrom:
            - secretRef:
                name: astronomy-db-creds
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: astronomy-data
