apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-omm
  namespace: astronomy
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: github-auth
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: ingest
          image: ghcr.io/toreau/astronomy-api@sha256:ca7f59cb0ea2ee423b9627a158a7f7868c2c331bf1029035d9f066cd2a8bc3c9
          command: ["dotnet", "Astronomy.DataIngestion.dll", "omm", "refresh"]
          envFrom:
            - secretRef:
                name: astronomy-db-creds
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: astronomy-data
