apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-omm
  namespace: astronomy
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: github-auth
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: ingest
          image: ghcr.io/toreau/astronomy-api@sha256:272a19d7ce29ad8926606ef87d6bf7fee64df2effe5492e72994f8e83a50669d
          command: ["dotnet", "Astronomy.DataIngestion.dll", "omm", "refresh"]
          envFrom:
            - secretRef:
                name: astronomy-db-creds
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: astronomy-data
