apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: sample-two
  namespace: sample
spec:
  image: nginxinc/nginx-unprivileged@sha256:197f252f060ed357f2ab98d4256762d7d107c76f18ad8f0b9d5178854611566d
  port: 8080
  replicas: 2
  ingresses:
    - sample-two.172.21.255.200.nip.io
