apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astronomy-db-data
  namespace: astronomy-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
