apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: astronomy-api
  namespace: astronomy
spec:
  image: ghcr.io/toreau/astronomy-api@sha256:72ad0e69bcd9a3e4ec7746281723ee05c43e4ebf719db9b095b1b5a468c90d54
  port: 8080
  ingresses:
    - astronomy.172.21.255.200.nip.io
  envFrom:
    - secret: astronomy-db-creds
  filesFrom:
    - persistentVolumeClaim: astronomy-data
      mountPath: /data
  readiness:
    path: /health/ready
    port: 8080
    initialDelay: 5
  liveness:
    path: /health/live
    port: 8080
    initialDelay: 20
    failureThreshold: 5
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi
  replicas:
    min: 1
    max: 2
    targetCpuUtilization: 80
