apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: astronomy-api
  namespace: astronomy
spec:
  image: ghcr.io/toreau/astronomy-api@sha256:2752508a052a096ca85c59726f2767cb82f45199b7a4fb9dc942f50eeda86d17
  port: 8080
  ingresses:
    - astronomy.172.21.255.200.nip.io
  envFrom:
    - secret: astronomy-db-creds
  filesFrom:
    - persistentVolumeClaim: astronomy-data
      mountPath: /data
  readiness:
    path: /health/ready
    port: 8080
    initialDelay: 5
  liveness:
    path: /health/live
    port: 8080
    initialDelay: 20
    failureThreshold: 5
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi
  replicas:
    min: 1
    max: 2
    targetCpuUtilization: 80
