apiVersion: skiperator.kartverket.no/v1beta1
kind: SKIPJob
metadata:
  name: ingest-naif
  namespace: astronomy
spec:
  image: astronomy-api:local
  command: ["dotnet", "Astronomy.DataIngestion.dll", "naif"]
  envFrom:
    - secret:
        name: astronomy-db-creds
  filesFrom:
    - persistentVolumeClaim: astronomy-data
      mountPath: /data
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
