name: validate

on:
  push:
  pull_request:

jobs:
  validate-apps:
    uses: toreau/gh-workflows/.github/workflows/manifest-validate.yml@main
    with:
      paths: "apps/"
      schemas-dir: "ci/schemas"

  validate-argocd:
    uses: toreau/gh-workflows/.github/workflows/manifest-validate.yml@main
    with:
      paths: "argocd/apps"
      yamllint-paths: "argocd/"
